(* frontend/elaborate.ml — emit .kf files from a theory + theorem.

   A .kf file is a self-contained input to the kernel verifier: it
   declares every axiom the certificate may cite, and states the goal. *)

let escape s =
  let buf = Buffer.create (String.length s + 4) in
  String.iter (fun c ->
    match c with
    | '"' -> Buffer.add_string buf "\\\""
    | '\\' -> Buffer.add_string buf "\\\\"
    | '\n' -> Buffer.add_string buf "\\n"
    | c -> Buffer.add_char buf c) s;
  Buffer.contents buf

let write_kf ~types ~consts ~axioms ~goal out_path =
  let oc = open_out out_path in
  Printf.fprintf oc ";; auto-generated by `elab`; self-contained kernel input\n";
  List.iter (fun (n, arity) ->
    if arity = 0 then Printf.fprintf oc "(type %s)\n" n
    else Printf.fprintf oc "(type %s %d)\n" n arity
  ) types;
  List.iter (fun (n, ty) ->
    Printf.fprintf oc "(const %s \"%s\")\n" n (escape (Kernel.Type.to_string ty))
  ) consts;
  List.iter (fun (n, t) ->
    Printf.fprintf oc "(axiom %s \"%s\")\n" n (escape (Kernel.Cert.pp_term t))
  ) axioms;
  Printf.fprintf oc "(goal \"%s\")\n" (escape (Kernel.Cert.pp_term goal));
  close_out oc

let elaborate_theorem thy theorem_name out_path =
  match List.assoc_opt theorem_name (Theory.theorems thy) with
  | None ->
      failwith ("elaborate_theorem: no theorem named " ^ theorem_name)
  | Some goal ->
      let types =
        List.filter_map (function
          | Theory.DType (n, k) -> Some (n, k) | _ -> None) thy.Theory.decls in
      let consts =
        List.filter_map (function
          | Theory.DConst (n, ty) -> Some (n, ty) | _ -> None) thy.Theory.decls in
      let axioms = Theory.axioms thy in
      write_kf ~types ~consts ~axioms ~goal out_path
